### ISSUE TITLE
Find out what Josh is planning for Drupal Dojo website.

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/drupaldojo-old#1]
We should hold off building any site for Drupal Dojo until we get more info from Josh regarding his plans for the Drupal 8 Dojo site.

**Comment by gusaus** [comment]
Josh mentioned in [#drupal-dojo Slack](https://drupal.slack.com/archives/C5NR9LLNT/p1500512153968313) he won't have any Dojo time until possibly the fall.

As [mentioned in this thread](https://drupal.slack.com/archives/C5NR9LLNT/p1499471880326164), we have the people, platform, and the Pantheon to build out, maintain, and sustain a solid D8 Drupal Dojo site right now. 

If Josh can point or txfer back the domain(s), we'd be able to take the lead and incorporate whatever he wanted to build.

**Comment by joshkoenig** [comment]
If you can build out a good site on Pantheon I'm happy to transfer the domain back! Please don't let that be a blocker. I'm happy to point it at the platform or xfer back to you if I don't get around to making use of anything.

In the mean-time, the real work of creating a site can proceed. Just use the Pantheon default platform domain. ;)

**Comment by gusaus** [comment]
Thanks @joshkoenig - based on the group of [mentors/leads coming onboard](https://github.com/DrupalOpenLearning/administration/issues/1), I'm thinking the site(s) are going to be pretty solid! 

We're basically using this repo as a staging/back to the future environment, but the plan is to dust off the [drupal group](https://groups.drupal.org/drupal-dojo) and [projects](https://github.com/DrupalOpenLearning/drupaldojo/issues/3) to develop in the open. Definitely want to make sure we're able to incorporate your ideas for features/functionality as we proceed.

With regards to Pantheon, we definitely want to be creative in the ways we provide value back to our hosting sponsor (websites, dojo sessions, events, podcasts, etc.). Ideally we'd be able to set up the proper environment to accommodate what @johnatasjmo is describing in #2 

Chime in if there's anything else we should sort out here... or we'll move the conversation to #drupal-dojo in Slack as we go!

**Comment by joshkoenig** [comment]
For my part, I would like to use the primary domain as a simple site that explains the Dojo concept to those who are not familiar, and helps people find the right place to engage. I think this could be up and running with less effort or pre-requisites.

Beyond that, I am most interested in tapping into the existing community of experts to start sharing best practices. There are enough developers with practice client experience who could share their techniques and learnings in "Dojo Style." 

For lessons, I want to try using Twitch as the medium. The gaming community has standardized the style and perfected a high grade stack for doing live streaming events with multiple participants and interactive chat: I think we can just run w/it by setting up a community channel there, which will automatically serve as an archive of all events, etc.

Ultimately the main site could serve as a kind of calendar for upcoming lessons, etc, but I'm still in favor of keeping it as simple as possible, and am wary of making the site a self-referential development project. ;)

However, I think the development of a distribution could be a great ongoing project. I would just suggest that the work of planning/executing/demonstrating that distribution be done separately from the "main" www.drupaldojo.com website.

That said, I won't be able to seriously work on this until the Fall, so if you get something awesome happening sooner... I'll happily get out of the way.

**Comment by ikit-claw** [comment]
I see no reason why we can't get that launched now. We seem to have a fair amount of support we could try and build on that momentum by pushing forward. Waiting will only lose us people. Less meetings more action ;)

**Comment by gusaus** [comment]
@ikit-claw Next step https://github.com/DrupalOpenLearning/drupaldojo/issues/4

**Comment by ikit-claw** [comment]
Josh hasn't really said anything about 'his plans' I've attempted to reach out him before should we try again? What do you think @lyndsey maybe he is just busy or doesn't really have much to add?

**Comment by gusaus** [comment]
Per https://github.com/DrupalOpenLearning/drupaldojo/issues/1#issuecomment-319173414 we're planning to go live with the new MVP on Pantheon by the first new session on Monday! 

@joshkoenig Would you now be able to point the domain(s) at the platform or xfer back to us? Whatever is quick and easy. Also, we'll need to do whatever is the current protocol for getting on the site approved for Pantheon community sponsorship. This is the dev instance we're still in the process of configuring. http://live-dojo-os.pantheonsite.io/

We can continue to discuss and work in requirements and suggestions from Josh https://github.com/DrupalOpenLearning/drupaldojo/issues/1#issuecomment-319814416 @lyndsey @ikit-claw @johnatasjmo @miesz-ko and other contributors in #drupal-dojo Slack before and after the initial relaunch. 

[updated url from dev]

**Comment by ikit-claw** [comment]
Since we referenced this and can still access it via the other topics closing this one.
