### ISSUE TITLE
Create sitemap

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#14]
Suggested Site Map :
 
Global elements:
Navigation
Header
Footer: copyright, contact address
Breadcrumbs
Home - Home page should include a login form for authenticated users, 
a dynamic list of up‐to‐3 most recent “public” ‐ flagged News items 
a dynamic list of up‐to‐5 upcoming “public”‐ flagged events
an area for home‐page specific content. RSS feed should be available for publicly available news and events.
News and Events - List of staff‐posted announcements, followed by a list of all upcoming posted events, sorted by date. Only items flagged as “public” should be viewable to anonymous users. Event titles should link to the event details page if main content area for that event is non‐null. News titles should link to the news item detail page. RSS feed should be available for publicly available news and events.
Blogs - List of 10 most recent blog posts by all users (title, short description, date, author, number of comments)
Individual blog home page - List of 10 most recent blog posts by selected users (title, lead copy, date, author, number of comments
Individual blog article page - Full text of blog posts, and all comments posted in a threaded form
Sponsors - Lists individuals, organizations or companies who have sponsored some part of the Dojo and/or related lessons, sessions and projects.
Corporate sponsors - Link to detail page with logo, company description, and members.
Individual sponsors - Link to detail page with badge and description.
Classifieds - Lists all posted classified ads.Only ads flagged as “public” should be viewable to anonymous users.
Discussions - A set of moderated message board forums
About - General information about the program
Directory - A list of all users with an account on the site
Contact - A Web‐based contact form that allows anonymous users to e‐mail program staff

**Comment by gusaus** [comment]
I created a wiki that should be more conducive for collaboration and tracking changes - https://github.com/DrupalOpenLearning/drupaldojo/wiki/Site-map

We'll need to work in some of the examples and suggestions from https://github.com/DrupalOpenLearning/drupaldojo/issues/4

**Comment by ikit-claw** [comment]
@gusaus when you say site wiki is this for the open social site or the GitHub?

**Comment by ikit-claw** [comment]
Wiki example exists for this now so reference that for the Dojo site.
