### ISSUE TITLE
Notes On OpenSocial set up (general)

### ISSUE THREAD

**Issue by lyndsey** [DrupalOpenLearning/drupaldojo-old#15]
The following are notes as the OpenSocial site was set up. Items her may be turned into issues, however it's primarily a place to reflect on the usability and changes we have made to opensocial to get it to meet our needs. It may be useful for others reviewing the history of the site later, or to the OpenSocial team.

User manual - http://lets.getopensocial.com/cm-sm-manual

**Comment by lyndsey** [comment]
First issue: contextual links UI is disabled - this means you can't add new fields to content items - you can edit but not add new fields (deliberate set up - we enabled)

Duplication of fields - Add Fields - Reference #bug 
![add field _ drupal dojo_2017-08-22_14-22-41](https://user-images.githubusercontent.com/1232190/29549177-b106707c-8745-11e7-8b00-999db2d4988f.png)

**Comment by lyndsey** [comment]
Home page config is next on the list. Added new topic item. Why no display home page? *whaa*

I'm thinking re content not displaying it's because I exist in Drupal as a user but I'm not in a group. 

Thinking it makes sense to name groups by project - then that taxonomy/categorisation flows through the site. Plus an operational level is fine. 

Hmmm I thought that by creating a group above in line with the taxonomy I would therefore make the taxonomy redundant... but out of the box there is no way to select to make a topic item visible for or connected to a group...

**Comment by lyndsey** [comment]
See - http://lets.getopensocial.com/manual-content-visibility "When a piece of content is created outside a group, the visibility of this piece of content can be configured for this specific content. When a piece of content is created inside a group, the visibility of this piece of content is set by the group it belongs to."

I can't see how to configure visability for specific content for a topic. Blergh testing event

**Comment by lyndsey** [comment]
Promoted to front page and sticky at top of list were hidden for Topic display form - enabled those.

**Comment by lyndsey** [comment]
Changing my topic to "Promoted to front page" did not make it display on front page.  It is in RHS box for newest topics, but it's not displaying in the /stream.

Also still can't seem to add my topic to a group

**Comment by lyndsey** [comment]
Ok, you must create the topic/content from within a group. It's a trap for seasoned Drupal players. 
Not being able to edit for a group is an issue 

http://lets.getopensocial.com/node/35 @gusaus and @ikit-claw can you both take note of this please, because as you add content you will need it to be added to a group so it can be categorised and displayed correctly. At this stage I think projects can be groups and I may remove that taxonomy term. However I do think a resource taxonomy is needed and this approach won't work.

**Comment by lyndsey** [comment]
Ok I have an issue. I think we should be going with content open and public by default, not locked in groups. This is a major issue because all of the build for open social is the visibility in groups. I don't mind tearing that down, but we need to make a decision. Locking the content away behind a registered layer is contra to everything we are trying to do...

At this point I'm resisting the urge to even enable views to see how this is put together btw...

Have created a task on permissions - #17

**Comment by lyndsey** [comment]
And still my new topic made in a group isn't displaying on the /stream page *grrrr*

Ohhh now it is - assume cache - that's fine.

**Comment by lyndsey** [comment]
Added text block field to basic block - it was just title. ? why - hopefullt this doesn't cause an issue

**Comment by lyndsey** [comment]
Appearance information isn't visible as per: http://dev-drupal-dojo-open-social.pantheonsite.io

I created a site manager account to test in case that was the issue, but no. Nothing stands out in roles. Will dig into modules.

Enabled color module.

Still don't have the same color/theme configuration options as per - http://lets.getopensocial.com/node/91

refers to Social Sass theme http://lets.getopensocial.com/manual-configure-corner-radius

Created task for this: #18

**Comment by lyndsey** [comment]
I'm unhappy not knowing how the home page content is rendered. I've got new topics displaying now in the main area, however they don't display to logged out users (only in RHS side bar)

**Comment by lyndsey** [comment]
I really like the image cropping function for the banner and the thumbnail. Add a content item and upload the image, then edit the item to see.

**Comment by lyndsey** [comment]
Gahhh, once you create a block editing the text isn't enabled - unless I'm missing a D8 thing here - I need to reveiw another site I have - block front end editing isn't working. 

See - http://dev-drupal-dojo-open-social.pantheonsite.io/node/25 the latest project module on the right has an incorrect link and I'm trying to edit.

Update some blocks in some regions do have an edit function - like in the footer

**Comment by lyndsey** [comment]
@ikit-claw this is the running task I have documenting changes and findings - I'm hesitant to make changes at this point, waiting to see what I can happily work around and tasking as I go. But you can see my stream of conciousness (for what it's worth) around reveiwing and assessment

**Comment by ikit-claw** [comment]
@lyndsey Thanks, this is all valuable information we can build into our docs. Priority 1 for today is to try and get someone to update the site for us who has pantheon experience try and cut through some of these issues we are having to battle.
