### ISSUE TITLE
Set up path alias

### ISSUE THREAD

**Issue by lyndsey** [DrupalOpenLearning/drupaldojo-old#16]
Have to get my head around opensocial content - but topics and events etc need path alias. 
Thinking that [group]/[node:title] is logical at this point

**Comment by ikit-claw** [comment]
@lyndsey that sounds like the logical path and we can always change later if needed.

**Comment by gusaus** [comment]
Has this been set up on the new site?

**Comment by ikit-claw** [comment]
@gusaus it's installed just needs defining. I wasn't asked to define it @lyndsey have you configured pathauto to your liking?

**Comment by ikit-claw** [comment]
This has been inactive since asking so I am closing.
