### ISSUE TITLE
Understanding group permissions

### ISSUE THREAD

**Issue by lyndsey** [DrupalOpenLearning/drupaldojo-old#17]
My preference is we make as much as possible open. Commenting etc can be left for registered - that's fine. It will be interesting to see if we get people to register and transition to communicating here or if it's just slack

I've set up a public group - my feeling is most projects will share these public settings too...

Public group 

Anon:

Can view comments
Can access group node overview (check this)
Can see nodes
Can enroll to events
Access posts in the group

Outsiders

Can add comments
Create new posts in group

**Comment by lyndsey** [comment]
I've created a "Public Project Group" Drupal projects that are made publicly accessible for learning and development. Posts, events and comments are made public.

**Comment by lyndsey** [comment]
Ahhhhhgghh you can't edit a group type once you've created it. So the problem is I have topics that I've created too.

**Comment by ikit-claw** [comment]
Thanks, @johnatasjmo if you can document all the changes you make in the process so we can add it into the Dojo docs that would be amazing.

**Comment by johnatasjmo** [comment]
Good. I will get some support on this one. It is an interesting topic.

**Comment by lyndsey** [comment]
@johnatasjmo I'm going to create a specific task for the issue of not being able to edit the group a content item eg topic, event has been assigned to. 

This task is general set up notes and assessment.

**Comment by lyndsey** [comment]
Here is a document I am working on to explain group permissions. Also see issue with public groups here -
#54  https://docs.google.com/document/d/17bAXWYilGAF3k3GkswN1Ehkjtht3ITg52Tol1045jGY/edit?usp=sharing

**Comment by johnatasjmo** [comment]
So how many groups to create: NB, Public, Open, Closed?
