### ISSUE TITLE
Color, font and rounded border config not available

### ISSUE THREAD

**Issue by lyndsey** [DrupalOpenLearning/drupaldojo-old#18]
Hey @ikit-claw do you mind looking at this? I know we could quite easily theme it out, but I'd still like to stick to out of box config as long as we can. 

Can you identify why we can't see these config options? I would have thought we'd have a pretty recent version of the site :/

Still don't have the same color/theme configuration options as per - http://lets.getopensocial.com/node/91

refers to Social Sass theme http://lets.getopensocial.com/manual-configure-corner-radius

**Comment by lyndsey** [comment]
I'm keen to try replacing the blue links with green for one - #0F832D

the blue #29abe2 doesn't pass WCAG contrast

**Comment by lyndsey** [comment]
Basic page (and assume all) don't accept png files - only gif jpg jpeg.

Updated to add png for image field in event, book, basic page and topic content type.

**Comment by ikit-claw** [comment]
@lyndsey 

I've asked about the colour in #opensocial because I see no config for it.

I do see the rounded edges though can you verify?

I'll add a task to update Basic pages to accept PNGs

**Comment by lyndsey** [comment]
@ikit-claw take a look at the links above - there should be config setting options for colour, radius of corners and fonts - this site doesn't - why?

**Comment by ikit-claw** [comment]
@lyndsey because according to the folks in OpenSocial that isn't part of the defaults.

**Comment by ikit-claw** [comment]
I think we need to do a howto for this given that it is not available by default. Kinda feels misleading to me, to be honest.

**Comment by ikit-claw** [comment]
@lyndsey since this available now via the theme options I am closing this ticket
