### ISSUE TITLE
Get variations of the Drupal Dojo image

### ISSUE THREAD

**Issue by lyndsey** [DrupalOpenLearning/drupaldojo-old#19]
Sorry to be a pain but I don't have photoshop - it would be good to get some variations of the drupal dogo banner to use in different things. Ie:

Banner no top text
Banner no text
Orange logo

Then I might splice it up a little to get the cloud and the house and the orange logo as seperate images.

**Comment by ikit-claw** [comment]
Do we have a high-quality copy? I have Photoshop :)

**Comment by gusaus** [comment]
@trevortwining was responsible for this fabulous work of art! 

![dojo-header1](https://user-images.githubusercontent.com/113996/29636481-a6bae42a-8805-11e7-8fb8-d9446d15adc9.png)

Pretty sure Trevor doesn't have the hi rez format sitting around?

**Comment by ikit-claw** [comment]
@lyndsey would this do I can sample it and resize

**Comment by lyndsey** [comment]
I'd like the original version with the clouds and the variations of the fonts too. The version in the site should be wider too. 

I'm going to cut some of the parts for backgrounds on the title too - then they show in the nice thumb view

**Comment by lyndsey** [comment]
The orange drupal icon for a favicon would be awesome too, for those of us that get twitchy about favicons...

**Comment by gusaus** [comment]
![dojologo](https://user-images.githubusercontent.com/113996/29654112-b904e9fe-8860-11e7-836d-bd14a59741c9.png)

![dojo-header](https://user-images.githubusercontent.com/113996/29654154-ead63e60-8860-11e7-8c14-800f5b53a5b4.png)

@trevortwining would you by any chance have any of the raw files tucked away somewhere?

**Comment by ikit-claw** [comment]
@gusaus is Trevortwining an artist? We could use more artwork.

See issue https://github.com/DrupalOpenLearning/drupaldojo/issues/25

**Comment by ikit-claw** [comment]
See Art work conv https://github.com/DrupalOpenLearning/drupaldojo/issues/44

Time for something new and fresh :)
