### ISSUE TITLE
Install path auto

### ISSUE THREAD

**Issue by lyndsey** [DrupalOpenLearning/drupaldojo-old#20]
The config for installing modules has been removed ? not sure if this is opensocial/necc for composer etc. So haven't played with it. 

I must have path auto - I cannot handle having non sef urls and I like this tool https://ftp.drupal.org/files/projects/pathauto-8.x-1.0.tar.gz

ctools needs adding - token already in the site. 

@ikit-claw you happy if I leave installing stuff to you? Only because one person managing is good, and I tend to just install and test and we all know how that can end...

**Comment by ikit-claw** [comment]
@lyndsey , while I am adding modules, do you want any others?

**Comment by lyndsey** [comment]
I'm taking a very cautious approach to installing modules atm - I think we need to identify and then reveiw whether we can live without them. Or at least make sure we have stretched opensocial far enough before we do install more. 

I cannot however live without sef paths.

**Comment by ikit-claw** [comment]
@lyndsey pathauto is now available
