### ISSUE TITLE
webx link is dead on https://groups.drupal.org/dojo-schedule

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#21]
Create a coming soon so on...

I can do this is required. 

Thoughts on a registration system for the events?

**Comment by gusaus** [comment]
We were using a sponsored gotowebinar account the last time around. Now we'll be using Twitch.tv. 

Think we can close out and followup here  https://github.com/DrupalOpenLearning/drupaldojo/issues/7
