### ISSUE TITLE
Duplicate Project boards?

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#22]
Do we have 2 boards for a specific reason I am not sure what happened but I seem to have taken over one all on my own haha.

@lyndsey @gusaus

**Comment by gusaus** [comment]
I thought it would be a good idea to have a [separate project board](https://github.com/DrupalOpenLearning/drupaldojo/projects/2) for tasks pertaining to managing and sustaining the Drupal Dojo program. This would include any ongoing work we do in all the related Dojo spaces https://github.com/DrupalOpenLearning/drupaldojo/wiki

Building and maintaining the Drupal Dojo website and any major components (such as the [#nfp & community theme](https://github.com/DrupalOpenLearning/drupaldojo/issues/5#issuecomment-322574528)) should be treated as a [separate project](https://github.com/DrupalOpenLearning/drupaldojo/projects/1) and is out of scope with regards of the day-day responsiblites of the program team.

Uhhh... that makes good sense, ya?!?

**Comment by ikit-claw** [comment]
I agree case closed
