### ISSUE TITLE
Art Work

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#25]
We could use some new art work for YouTube. 
You need to make it to the specific sizes so I doubt the current image will be viable. 

Suggestions?

Anyone know someone who might make something for the channel?

We should also look to clearly identify the differences between Drupal Open Learning and the Drupal Dojo including separate art work for that more professional look.

**Comment by lyndsey** [comment]
Here is link to Drupal logos https://www.drupal.org/about/media-kit/logos

**Comment by ikit-claw** [comment]
Added the banner to YouTube for now. Not great but it is something to show activity.

**Comment by ikit-claw** [comment]
See https://github.com/DrupalOpenLearning/drupaldojo/issues/44

Should be able to get all our art needs just need to drill down on what we like the feel of.
