### ISSUE TITLE
Evaluate/set up 'Skill' vocabulary

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#26]
When listing a person's skills we need to make a list of skills they can do. So we can identify skill sets and what assets we have this would be a great stepping stone for the mentor scheme idea. 

Categories:

- Themer
- Site Builder
- Developer

Developer

Levels:

- Novice
- Junior
- Senior

Skills:

- Git
- HTML
- HTML5
- CSS
- CSS3
- Sass
- Bootstrap
- JS
- PHP
- Symfony
- Drush
- DrupalConsole
- Twig

We need skill tree's for these to entries specific skills and level of experience. 

Should we list skills as a subset or just list all skills?

**Comment by johnatasjmo** [comment]
I'd say just as skill list. Like tags the way freelancer.com or any freelancer site works. I think the skills list is good to start, users can add more.

**Comment by ikit-claw** [comment]
Updated and added
