### ISSUE TITLE
Create Dojo submission for sessions

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#27]
We can easily put together a Dojo session submission system to enable hosters to provide all the information we need. Via webforms module. 

I know we have the Drupal Group but the fact is that is a rather dated approach we can manually add session details for people to the group. Once we have confirmed the session.

**Comment by gusaus** [comment]
Ideally we should have the session producers create the event directly from the Dojo group - https://groups.drupal.org/node/add/event?gids[]=2191

As long as we provide clear guidelines https://github.com/DrupalOpenLearning/drupaldojo/issues/7#issuecomment-324459863, the submission process should not be something Dojo organizers need to manage themselves.

The benefit of this approach is Dojo events will appear on aggregators like https://www.drupical.com/ -- possibly we could incorporate a similar process for pulling events into the website?!? https://github.com/DrupalOpenLearning/drupaldojo/issues/10

**Comment by ikit-claw** [comment]
Events section is ready to rock.
