### ISSUE TITLE
What to ask for with a Drupal Dojo session

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#28]
Presenter name: 
Title of Session: 
Session details:
Date / time / zone : 
Expected duration : 
Do they need help with the setup: 
Sponsor:?
Supporting Organisation:?

**Comment by johnatasjmo** [comment]
Same as meetup. Location with coordinates. Maybe level of knowledge (basic, intermediate, advanced).

**Comment by ikit-claw** [comment]
Thanks will check against the meetup. 

We've booked our first session

**Comment by gusaus** [comment]
Presenters will be able to provide most of this info when they create an event from the Dojo group https://groups.drupal.org/node/add/event?gids[]=2191  https://github.com/DrupalOpenLearning/drupaldojo/issues/27#issuecomment-326680883

**Comment by ikit-claw** [comment]
@gusaus is this different to the other registration page? Sorry am not a drupal-groups veteran

**Comment by ikit-claw** [comment]
Thanks, I know what we need now closing this.
