### ISSUE TITLE
New Dev

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#29]
Because of the countless issues, we have encountered trying to update with composer and current lack of people coming forward to assist with it I and Lyndsey made the choice to spin up a fresh up to Dev copy of Open Social. So that we can clear the issues permanently. 

Anyone wanting access should ping me and/or Lyndsey to get an account approved.

I think it is critical at this time that we get the site working to add a level of professionalism to the Dojo.

**Comment by gusaus** [comment]
@ikit-claw Sounds like we'll have plenty of material for tutorials, case studies, and Dojo sessions about this site building experience (:

What's the url for the current dev environment. Can you add me?

**Comment by ikit-claw** [comment]
It's here http://dev-dojo-os.pantheonsite.io/ just ping me or Lyndsey to active you on slack

**Comment by ikit-claw** [comment]
Now the 3 of us are admins we can close this anyone wanting to assist can message us for activation.
