### ISSUE TITLE
Update guidelines for presenting and attending a live Dojo session

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/drupaldojo-old#30]
I dug up a very old, but pretty thorough wiki regarding presenting and attending a live Dojo session... created by the one and only webchick herself. 

https://groups.drupal.org/node/3287

Thankfully we can switch out the skype, vnc, and IRC with slack and twitch... updating/detailing other roles (presenter, host, attendee, transcription/documentation manager) would definitely be useful.

**Comment by ikit-claw** [comment]
Guideline updated
