### ISSUE TITLE
Post your daily goal 

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#31]
Post your daily goal and if achieved to group team chat.

I'd like to know what people are doing so we can co ordinate a little better.

For me, we need a hard deadline of the 8th to achieve the site launch.

**Comment by ikit-claw** [comment]
![todays mission](https://user-images.githubusercontent.com/17749942/29997583-b88901c6-900e-11e7-9b52-0cb12ec3fee6.png)

This is why I am busy this weekend. I hope to get this done over the weekend though

**Comment by gusaus** [comment]
My goal is to jump back into a regular commitment beginning Tuesday. Based on how the dev site is progressing.. thank you @lyndsey and @ikit-claw... I'm confident we're bringing the Dojo back for the long run.

**Comment by ikit-claw** [comment]
Closing this now we have discussed what we are doing
