### ISSUE TITLE
Decision on registered user access and functions

### ISSUE THREAD

**Issue by lyndsey** [DrupalOpenLearning/drupaldojo-old#33]
OS is designed to be a closed community. My preference is to keep it as open as possible. This needs to be clearly defined because once you have assigned a content item to a user group aas far as I can see you can't edit it.

**Comment by lyndsey** [comment]
my personal preference is:

1. - Initially no login required to access content, posts, events, comments. 
2. - I don't care either way re comments. 
3. - Login should be encouraged with functions
4. - Remove the big default home page login/signup and replace with more subtle call to action on right of page and in footer

**Comment by lyndsey** [comment]
Topics and events are public but groups and group content isn't.
You can set up groups so that their content is visible to non members of the group, but it means that they still need a login to see it. 

The easiest approach if we want to open content up will be to change the community permission settings and then create a third access role. As community content is set by default for most things I think this is the most foolproof way.

**Comment by gusaus** [comment]
I've yet to really dig in and get to know Open Social, but I agree 'open and public' should be the norm.

As mentioned in https://github.com/DrupalOpenLearning/drupaldojo/issues/23, I think a site like Meetup.com could serve as a guide:
https://www.meetup.com/Austin-Drupal-Users-Group/
https://www.meetup.com/Austin-Drupal-Users-Group/events/243031231/

**Comment by ikit-claw** [comment]
Was discussed at the group voice meeting
