### ISSUE TITLE
Get a domain name 

### ISSUE THREAD

**Issue by ikit-claw** [DrupalOpenLearning/drupaldojo-old#36]
Sort out what we are going to do for a domain name for the site.

**Comment by gusaus** [comment]
Per https://github.com/DrupalOpenLearning/drupaldojo/issues/1#issuecomment-327862689, we should have drupaldojo.com and drupaldojo.org pointed to the site.

**Comment by gusaus** [comment]
Still awaiting word back from @joshkoenig regarding the pointing or transferring back of the the domains. 

Now that we're back to doing sessions beginning yesterday, we should go live with http://live-dojo-os.pantheonsite.io/ before the next ones.

**Comment by joshkoenig** [comment]
Whoa awesome! Happy to point it there. :)

**Comment by joshkoenig** [comment]
DNS is still propogating and HTTPS is being provisioned, but I can route .org as of now:

http://drupaldojo.org/

Also made this a "developer community project" and upgraded to Pro.

**Comment by gusaus** [comment]
Amazing - thank you so much! @ikit-claw We need to add the Pantheon logo in the footer and will also credit on the sponsor section when we get that set up. 

Anything else we need to do (aside from working in your Dojo goals and vision for the reboot)!!
