### ISSUE TITLE
Set up About page

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/drupaldojo-old#37]
I added an abbreviated description of the Dojo from years past - 
https://github.com/DrupalOpenLearning/drupaldojo/wiki/About

Possibly we could make some additions/revisions on the wiki as a draft

**Comment by ikit-claw** [comment]
@gusaus I could use a few paragraphs from you about what you think the dojo is

**Comment by gusaus** [comment]
@ikit-claw I the previous blurb above in the issue description. 

Not sure who wrote this, but it's pretty good! http://dev-drupal-dojo-open-social.pantheonsite.io/node/24

Also would be good to get some thoughts from the Dojo father @joshkoenig regarding 'Dojo style 2017'! https://github.com/DrupalOpenLearning/drupaldojo/issues/1#issuecomment-319814416

**Comment by ikit-claw** [comment]
@gusaus will add the old blurb to the new site then :)

**Comment by ikit-claw** [comment]
Added

**Comment by gusaus** [comment]
Does hiding the big ass hero block look better on pages? 
http://live-dojo-os.pantheonsite.io/About

Also 
![about drupal dojo 2017-09-08 18-21-43](https://user-images.githubusercontent.com/113996/30233292-9249a9e4-94c2-11e7-8374-6873fee12638.png)

**Comment by ikit-claw** [comment]
Good point The creator information should be turned off but it is still displaying. I will have a word see if I can figure it out.

**Comment by ikit-claw** [comment]
I'm persisting with the opensocial issue but we may have to just live with this for awhile.

https://drupal.slack.com/files/U24KS2TCY/F71Q3V2AH/about___drupal_dojo_-_google_chrome_2017-09-12_09.53.34.png

**Comment by ikit-claw** [comment]
It is hard coded into node-full.html.twig @gusaus I can subtheme it out if you like? @lyndsey thoughts before I proceed?

**Comment by ikit-claw** [comment]
Confirmed bug and should not have to hardcode my way around it they say now.

**Comment by ikit-claw** [comment]
Fixed in 1.5
