### ISSUE TITLE
Set up 'Category or track' vocabulary

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/drupaldojo-old#38]
Per our discussion we should use Drupalcons and Drupalcamps as a guide in terms of how to categorize sessions and tracks. 

I believe the Drupalcon tracks are standardized with 'official' tracks being added from time to time. I'm wondering if it would be benefit the community to have identical tracks. In doing so, we could provide an outlet for multiple presentations between Drupalcons and camps.

If we were looking at https://events.drupal.org/vienna2017/tracks as a guide - there could be a group for each of these? Possibly that's overkill to begin. What are your thoughts?

- Being Human
- Business
- Coding and Development
- Core Conversations
- DevOps
- Drupal Showcase
- Front End
- Horizons
- Performance and Scaling
- PHP
- Project Management
- Site Building
- Symfony

**Comment by gusaus** [comment]
Quite possibly following how Drupalcon breaks out tracks would be overkill to begin with. We could actually start by creating groups for tracks or initiatives in which we have some role - 

- Building with Drupal https://groups.drupal.org/node/52023 
- Drupal Community Spotlight - https://www.drupal.org/association/blog/kickstarting-the-drupal-community-spotlight
- Drupal for Nonprofits (or whatever would be a better title)

That type of thing.... 

Thoughts @lyndsey and @ikit-claw ?

**Comment by ikit-claw** [comment]
@gusaus added
