### ISSUE TITLE
Evaluate/set up 'Session Type' vocabulary

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/drupaldojo-old#41]
We had a vocabulary 'Type' on the previous website with the following terms - 

- Lesson, Tutorial, or Howto
- Workshop, Sprint, or Project
- Discussion, Coffeetalk, or BOF
- Showcase, Case Study, or Demo

Would this be useful to categorize sessions in this fashion? I think this may overlap with the 'Event types' vocabulary already set up?

**Comment by ikit-claw** [comment]
@gusaus BOF?
