### ISSUE TITLE
Fix & Explore: Bugs in public groups

### ISSUE THREAD

**Issue by lyndsey** [DrupalOpenLearning/drupaldojo-old#54]
Have only created one public group so have not tested to replicate. Issues are with Community Spotlight group - created as a public group - when i created it added me as a member twice, although I couldn't see my name in the member list. Tried to add a topic to the group - got "You are not authorised to access this resource" error message. Removed myself from group and readded - issue still occurs. 

Presently we cannot add new topics to this public group. 

We need a different level of visibility, access and transparency to most intranets so this is important to resolve.

**Comment by lyndsey** [comment]
A few d.o. tasks that are related (note I have not assessed in detail)
https://www.drupal.org/node/2859563
https://www.drupal.org/node/2890526

**Comment by gusaus** [comment]
Assuming we're talking about http://drupaldojo.com/spotlight-group

I joined and tried to create both a topic and event. Both instances I got the same message -
![group events drupal dojo 2017-10-02 17-11-26](https://user-images.githubusercontent.com/113996/31099655-bd060cce-a794-11e7-83ee-7c8a80e89dbc.png)

Upon digging around a bit, it looks like the issue may be the plugins need to be installed. Check out the difference between the following - 

**Open group**
http://drupaldojo.com/admin/group/types/manage/open_group/content
![configure available content drupal dojo 2017-10-02 17-26-54](https://user-images.githubusercontent.com/113996/31100299-e427200c-a796-11e7-8cf8-807a78879bdc.png)


**Public group**
http://drupaldojo.com/admin/group/types/manage/public_group/content
![configure available content drupal dojo 2017-10-02 17-32-23](https://user-images.githubusercontent.com/113996/31100508-a7e082b8-a797-11e7-8fce-0564e9539be8.png)

So I 'think' we just need to install plugins for topics, events, and whatever else we should have available in an 'open group'?

It would be great if someone on the Open Social side could advise/mentor us through this configuration.

**Comment by gusaus** [comment]
@lyndsey Does the 'public group' ship with Open Social or was it a group type we set up? The reason we could post events or topics is they needed to be installed - 

![image](https://user-images.githubusercontent.com/113996/31523164-eade01e0-af7f-11e7-94d0-5ee70497df83.png)

We also have the option of enabling 'page' and 'book page' if we choose.

The next step is setting the appropriate permissions for whatever was just enabled - I'm still working on ensuring anything posted to this public group type is visible to all. 

![edit group type permissions drupal dojo 2017-10-12 19-08-28](https://user-images.githubusercontent.com/113996/31523329-bc9a6e62-af80-11e7-97f4-f79b808080f4.png)

Is that close to how we want this group type for function?

**Comment by gusaus** [comment]
Just noticing https://github.com/DrupalOpenLearning/drupaldojo/issues/17#issue-251866909 is about the public group type @lyndsey set up.

**Comment by ikit-claw** [comment]
@gusaus I think we have a handle on the group's stuff. The public group works @lyndsey isn't going to be available much.

**Comment by gusaus** [comment]
This issue should be resolved once we upgrade to the latest version. If not we'll reopen.
