### ISSUE TITLE
Process: One issue, one task

### ISSUE THREAD

**Issue by lyndsey** [DrupalOpenLearning/drupaldojo-old#8]
I'm seeing that these tasks are getting tangled like the slack threads. The issue with  this in a task/issues management queue is that as soon as there is confusion over task/role/responsibility items get dropped. Already I'm seeing a contridiction in assignees.

Like this one #2 the process followed already existed, then Daniel said he'd document it specifically for this environment, and then Chandeep was assigned. If people are assigned to help then the person responsible for the task can add the specific element they need help with preferably as a new task and close it once done. 

Let's be super excited about lots of short, clear tasks and closing things frequently.

**Comment by ikit-claw** [comment]
I plan to review everything today and update a lot of stuff. I think he means that chan can official be part of the team more than he has a specific task.

**Comment by lyndsey** [comment]
Sounds great - ta!

**Comment by ikit-claw** [comment]
Let's celebrate by closing an issue lol
